-- MySQL Script generated by MySQL Workbench
-- Sat Apr 27 17:01:12 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema capstoneproject
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema capstoneproject
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `capstoneproject` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `capstoneproject` ;

-- -----------------------------------------------------
-- Table `capstoneproject`.`coursecategory`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `capstoneproject`.`coursecategory` (
  `CatagoryID` CHAR(36) CHARACTER SET 'ascii' NOT NULL,
  `Category` VARCHAR(50) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_0900_ai_ci' NOT NULL,
  `CreatedBy` VARCHAR(120) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_0900_ai_ci' NOT NULL,
  `CreatedAt` DATETIME NOT NULL,
  `ModifiedBy` VARCHAR(120) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_0900_ai_ci' NOT NULL,
  `ModifiedAt` DATETIME NOT NULL,
  PRIMARY KEY (`CatagoryID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `capstoneproject`.`courselevels`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `capstoneproject`.`courselevels` (
  `LevelID` CHAR(36) CHARACTER SET 'ascii' NOT NULL,
  `Level` VARCHAR(50) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_0900_ai_ci' NOT NULL,
  `CreatedBy` VARCHAR(120) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_0900_ai_ci' NOT NULL,
  `CreatedAt` DATETIME NOT NULL,
  `ModifiedBy` VARCHAR(120) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_0900_ai_ci' NOT NULL,
  `ModifiedAt` DATETIME NOT NULL,
  PRIMARY KEY (`LevelID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `capstoneproject`.`course`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `capstoneproject`.`course` (
  `CourseID` CHAR(36) CHARACTER SET 'ascii' NOT NULL,
  `Title` VARCHAR(50) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_0900_ai_ci' NOT NULL,
  `Description` LONGTEXT CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_0900_ai_ci' NOT NULL,
  `Validity` INT NOT NULL,
  `Duration` DECIMAL(65,30) NOT NULL,
  `Thumbnail` LONGTEXT CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_0900_ai_ci' NOT NULL,
  `IsActive` TINYINT(1) NOT NULL,
  `IsAvailable` TINYINT(1) NOT NULL,
  `CreatedBy` VARCHAR(120) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_0900_ai_ci' NOT NULL,
  `CreatedAt` DATETIME NOT NULL,
  `ModifiedBy` VARCHAR(120) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_0900_ai_ci' NOT NULL,
  `ModifiedAt` DATETIME NOT NULL,
  `LevelID` CHAR(36) CHARACTER SET 'ascii' NOT NULL,
  `CatagoryID` CHAR(36) CHARACTER SET 'ascii' NOT NULL,
  PRIMARY KEY (`CourseID`),
  INDEX `IX_Course_CatagoryID` (`CatagoryID` ASC) VISIBLE,
  INDEX `IX_Course_LevelID` (`LevelID` ASC) VISIBLE,
  CONSTRAINT `FK_Course_CourseCategory_CatagoryID`
    FOREIGN KEY (`CatagoryID`)
    REFERENCES `capstoneproject`.`coursecategory` (`CatagoryID`)
    ON DELETE CASCADE,
  CONSTRAINT `FK_Course_CourseLevels_LevelID`
    FOREIGN KEY (`LevelID`)
    REFERENCES `capstoneproject`.`courselevels` (`LevelID`)
    ON DELETE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `capstoneproject`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `capstoneproject`.`users` (
  `UserID` CHAR(36) CHARACTER SET 'ascii' NOT NULL,
  `Email` VARCHAR(50) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_0900_ai_ci' NOT NULL,
  `Password` VARCHAR(30) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_0900_ai_ci' NOT NULL,
  `Role` VARCHAR(10) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_0900_ai_ci' NOT NULL,
  `UnblockRequest` TINYINT(1) NOT NULL,
  `AccountStatus` TINYINT(1) NOT NULL,
  `UserLastLogin` DATETIME NOT NULL,
  `CreatedBy` LONGTEXT CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_0900_ai_ci' NOT NULL,
  `CreatedAt` DATETIME NOT NULL,
  `ModifiedBy` LONGTEXT CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_0900_ai_ci' NOT NULL,
  `ModifiedAt` DATETIME NOT NULL,
  PRIMARY KEY (`UserID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `capstoneproject`.`enrollments`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `capstoneproject`.`enrollments` (
  `EnrollmentID` CHAR(36) CHARACTER SET 'ascii' NOT NULL,
  `UserID` CHAR(36) CHARACTER SET 'ascii' NOT NULL,
  `CourseID` CHAR(36) CHARACTER SET 'ascii' NOT NULL,
  `EnrollmentDate` DATETIME NOT NULL,
  `EnrollStatus` TINYINT(1) NOT NULL,
  `CreatedBy` LONGTEXT CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_0900_ai_ci' NOT NULL,
  `CreatedAt` DATETIME NOT NULL,
  `ModifiedBy` LONGTEXT CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_0900_ai_ci' NOT NULL,
  `ModifiedAt` DATETIME NOT NULL,
  PRIMARY KEY (`EnrollmentID`),
  INDEX `IX_Enrollments_CourseID` (`CourseID` ASC) VISIBLE,
  INDEX `IX_Enrollments_UserID` (`UserID` ASC) VISIBLE,
  CONSTRAINT `FK_Enrollments_Course_CourseID`
    FOREIGN KEY (`CourseID`)
    REFERENCES `capstoneproject`.`course` (`CourseID`)
    ON DELETE CASCADE,
  CONSTRAINT `FK_Enrollments_Users_UserID`
    FOREIGN KEY (`UserID`)
    REFERENCES `capstoneproject`.`users` (`UserID`)
    ON DELETE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `capstoneproject`.`feedbackquestions`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `capstoneproject`.`feedbackquestions` (
  `FeedbackQuestionId` CHAR(36) CHARACTER SET 'ascii' NOT NULL,
  `CourseID` CHAR(36) CHARACTER SET 'ascii' NOT NULL,
  `QuestionNo` INT NOT NULL,
  `Question` LONGTEXT CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_0900_ai_ci' NOT NULL,
  PRIMARY KEY (`FeedbackQuestionId`),
  INDEX `IX_FeedbackQuestions_CourseID` (`CourseID` ASC) VISIBLE,
  CONSTRAINT `FK_FeedbackQuestions_Course_CourseID`
    FOREIGN KEY (`CourseID`)
    REFERENCES `capstoneproject`.`course` (`CourseID`)
    ON DELETE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `capstoneproject`.`feedbackresponses`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `capstoneproject`.`feedbackresponses` (
  `FeedbackResponseId` CHAR(36) CHARACTER SET 'ascii' NOT NULL,
  `UserID` CHAR(36) CHARACTER SET 'ascii' NOT NULL,
  `Response` LONGTEXT CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_0900_ai_ci' NOT NULL,
  `FeedbackQuestionId` CHAR(36) CHARACTER SET 'ascii' NOT NULL,
  PRIMARY KEY (`FeedbackResponseId`),
  INDEX `IX_FeedbackResponses_FeedbackQuestionId` (`FeedbackQuestionId` ASC) VISIBLE,
  INDEX `IX_FeedbackResponses_UserID` (`UserID` ASC) VISIBLE,
  CONSTRAINT `FK_FeedbackResponses_FeedbackQuestions_FeedbackQuestionId`
    FOREIGN KEY (`FeedbackQuestionId`)
    REFERENCES `capstoneproject`.`feedbackquestions` (`FeedbackQuestionId`)
    ON DELETE CASCADE,
  CONSTRAINT `FK_FeedbackResponses_Users_UserID`
    FOREIGN KEY (`UserID`)
    REFERENCES `capstoneproject`.`users` (`UserID`)
    ON DELETE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `capstoneproject`.`topic`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `capstoneproject`.`topic` (
  `TopicID` CHAR(36) CHARACTER SET 'ascii' NOT NULL,
  `Name` VARCHAR(50) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_0900_ai_ci' NOT NULL,
  `Description` VARCHAR(250) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_0900_ai_ci' NOT NULL,
  `IsActive` TINYINT(1) NOT NULL,
  `CreatedBy` VARCHAR(120) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_0900_ai_ci' NOT NULL,
  `CreatedAt` DATETIME NOT NULL,
  `ModifiedBy` VARCHAR(120) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_0900_ai_ci' NOT NULL,
  `ModifiedAt` DATETIME NOT NULL,
  `CourseID` CHAR(36) CHARACTER SET 'ascii' NOT NULL,
  PRIMARY KEY (`TopicID`),
  INDEX `IX_Topic_CourseID` (`CourseID` ASC) VISIBLE,
  CONSTRAINT `FK_Topic_Course_CourseID`
    FOREIGN KEY (`CourseID`)
    REFERENCES `capstoneproject`.`course` (`CourseID`)
    ON DELETE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `capstoneproject`.`materials`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `capstoneproject`.`materials` (
  `MaterialID` CHAR(36) CHARACTER SET 'ascii' NOT NULL,
  `Name` VARCHAR(50) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_0900_ai_ci' NOT NULL,
  `Filepath` LONGTEXT CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_0900_ai_ci' NOT NULL,
  `Duration` DECIMAL(65,30) NOT NULL,
  `Type` VARCHAR(15) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_0900_ai_ci' NOT NULL,
  `IsActive` TINYINT(1) NOT NULL,
  `IsAvailable` TINYINT(1) NOT NULL,
  `CreatedBy` VARCHAR(120) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_0900_ai_ci' NOT NULL,
  `CreatedAt` DATETIME NOT NULL,
  `ModifiedBy` VARCHAR(120) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_0900_ai_ci' NOT NULL,
  `ModifiedAt` DATETIME NOT NULL,
  `TopicID` CHAR(36) CHARACTER SET 'ascii' NOT NULL,
  `CourseID` CHAR(36) CHARACTER SET 'ascii' NOT NULL,
  PRIMARY KEY (`MaterialID`),
  INDEX `IX_Materials_CourseID` (`CourseID` ASC) VISIBLE,
  INDEX `IX_Materials_TopicID` (`TopicID` ASC) VISIBLE,
  CONSTRAINT `FK_Materials_Course_CourseID`
    FOREIGN KEY (`CourseID`)
    REFERENCES `capstoneproject`.`course` (`CourseID`)
    ON DELETE CASCADE,
  CONSTRAINT `FK_Materials_Topic_TopicID`
    FOREIGN KEY (`TopicID`)
    REFERENCES `capstoneproject`.`topic` (`TopicID`)
    ON DELETE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `capstoneproject`.`passwordhistories`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `capstoneproject`.`passwordhistories` (
  `PasswordID` CHAR(36) CHARACTER SET 'ascii' NOT NULL,
  `OldPassword` VARCHAR(30) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_0900_ai_ci' NOT NULL,
  `NewPassword` VARCHAR(30) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_0900_ai_ci' NOT NULL,
  `CreatedBy` LONGTEXT CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_0900_ai_ci' NOT NULL,
  `CreatedAt` DATETIME NOT NULL,
  `ModifiedBy` LONGTEXT CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_0900_ai_ci' NOT NULL,
  `ModifiedAt` DATETIME NOT NULL,
  `UserID` CHAR(36) CHARACTER SET 'ascii' NOT NULL,
  PRIMARY KEY (`PasswordID`),
  INDEX `IX_PasswordHistories_UserID` (`UserID` ASC) VISIBLE,
  CONSTRAINT `FK_PasswordHistories_Users_UserID`
    FOREIGN KEY (`UserID`)
    REFERENCES `capstoneproject`.`users` (`UserID`)
    ON DELETE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `capstoneproject`.`profiles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `capstoneproject`.`profiles` (
  `ProfileID` CHAR(36) CHARACTER SET 'ascii' NOT NULL,
  `FirstName` VARCHAR(50) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_0900_ai_ci' NOT NULL,
  `LastName` VARCHAR(50) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_0900_ai_ci' NOT NULL,
  `DOB` DATE NOT NULL,
  `Gender` VARCHAR(20) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_0900_ai_ci' NOT NULL,
  `ContactNumber` VARCHAR(15) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_0900_ai_ci' NOT NULL,
  `Stream` VARCHAR(50) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_0900_ai_ci' NOT NULL,
  `UserID` CHAR(36) CHARACTER SET 'ascii' NOT NULL,
  `CreatedBy` LONGTEXT CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_0900_ai_ci' NOT NULL,
  `CreatedAt` DATETIME NOT NULL,
  `ModifiedBy` LONGTEXT CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_0900_ai_ci' NOT NULL,
  `ModifiedAt` DATETIME NOT NULL,
  PRIMARY KEY (`ProfileID`),
  INDEX `IX_Profiles_UserID` (`UserID` ASC) VISIBLE,
  CONSTRAINT `FK_Profiles_Users_UserID`
    FOREIGN KEY (`UserID`)
    REFERENCES `capstoneproject`.`users` (`UserID`)
    ON DELETE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `capstoneproject`.`quizzes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `capstoneproject`.`quizzes` (
  `QuizId` CHAR(36) CHARACTER SET 'ascii' NOT NULL,
  `CourseID` CHAR(36) CHARACTER SET 'ascii' NOT NULL,
  `NameOfQuiz` LONGTEXT CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_0900_ai_ci' NOT NULL,
  `Duration` INT NOT NULL,
  `PassMark` INT NOT NULL,
  PRIMARY KEY (`QuizId`),
  INDEX `IX_Quizzes_CourseID` (`CourseID` ASC) VISIBLE,
  CONSTRAINT `FK_Quizzes_Course_CourseID`
    FOREIGN KEY (`CourseID`)
    REFERENCES `capstoneproject`.`course` (`CourseID`)
    ON DELETE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `capstoneproject`.`quizquestions`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `capstoneproject`.`quizquestions` (
  `QuizQuestionId` CHAR(36) CHARACTER SET 'ascii' NOT NULL,
  `QuizId` CHAR(36) CHARACTER SET 'ascii' NOT NULL,
  `QuestionNo` INT NOT NULL,
  `Question` LONGTEXT CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_0900_ai_ci' NOT NULL,
  PRIMARY KEY (`QuizQuestionId`),
  INDEX `IX_QuizQuestions_QuizId` (`QuizId` ASC) VISIBLE,
  CONSTRAINT `FK_QuizQuestions_Quizzes_QuizId`
    FOREIGN KEY (`QuizId`)
    REFERENCES `capstoneproject`.`quizzes` (`QuizId`)
    ON DELETE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `capstoneproject`.`questionoptions`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `capstoneproject`.`questionoptions` (
  `QuestionOptionId` CHAR(36) CHARACTER SET 'ascii' NOT NULL,
  `Option` LONGTEXT CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_0900_ai_ci' NOT NULL,
  `IsCorrect` TINYINT(1) NOT NULL,
  `QuizQuestionId` CHAR(36) CHARACTER SET 'ascii' NOT NULL,
  PRIMARY KEY (`QuestionOptionId`),
  INDEX `IX_QuestionOptions_QuizQuestionId` (`QuizQuestionId` ASC) VISIBLE,
  CONSTRAINT `FK_QuestionOptions_QuizQuestions_QuizQuestionId`
    FOREIGN KEY (`QuizQuestionId`)
    REFERENCES `capstoneproject`.`quizquestions` (`QuizQuestionId`)
    ON DELETE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `capstoneproject`.`userattempts`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `capstoneproject`.`userattempts` (
  `UserAttemptId` CHAR(36) CHARACTER SET 'ascii' NOT NULL,
  `UserID` CHAR(36) CHARACTER SET 'ascii' NOT NULL,
  `QuizId` CHAR(36) CHARACTER SET 'ascii' NOT NULL,
  `AttemptCount` INT NOT NULL,
  `StartTime` DATETIME NOT NULL,
  `EndTime` DATETIME NOT NULL,
  `Score` FLOAT NOT NULL,
  PRIMARY KEY (`UserAttemptId`),
  INDEX `IX_UserAttempts_QuizId` (`QuizId` ASC) VISIBLE,
  INDEX `IX_UserAttempts_UserID` (`UserID` ASC) VISIBLE,
  CONSTRAINT `FK_UserAttempts_Quizzes_QuizId`
    FOREIGN KEY (`QuizId`)
    REFERENCES `capstoneproject`.`quizzes` (`QuizId`)
    ON DELETE CASCADE,
  CONSTRAINT `FK_UserAttempts_Users_UserID`
    FOREIGN KEY (`UserID`)
    REFERENCES `capstoneproject`.`users` (`UserID`)
    ON DELETE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `capstoneproject`.`useranswers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `capstoneproject`.`useranswers` (
  `UserAnswerId` CHAR(36) CHARACTER SET 'ascii' NOT NULL,
  `UserAttemptId` CHAR(36) CHARACTER SET 'ascii' NOT NULL,
  `QuizQuestionId` CHAR(36) CHARACTER SET 'ascii' NOT NULL,
  `QuestionOptionId` CHAR(36) CHARACTER SET 'ascii' NOT NULL,
  PRIMARY KEY (`UserAnswerId`),
  INDEX `IX_UserAnswers_QuestionOptionId` (`QuestionOptionId` ASC) VISIBLE,
  INDEX `IX_UserAnswers_QuizQuestionId` (`QuizQuestionId` ASC) VISIBLE,
  INDEX `IX_UserAnswers_UserAttemptId` (`UserAttemptId` ASC) VISIBLE,
  CONSTRAINT `FK_UserAnswers_QuestionOptions_QuestionOptionId`
    FOREIGN KEY (`QuestionOptionId`)
    REFERENCES `capstoneproject`.`questionoptions` (`QuestionOptionId`)
    ON DELETE CASCADE,
  CONSTRAINT `FK_UserAnswers_QuizQuestions_QuizQuestionId`
    FOREIGN KEY (`QuizQuestionId`)
    REFERENCES `capstoneproject`.`quizquestions` (`QuizQuestionId`)
    ON DELETE CASCADE,
  CONSTRAINT `FK_UserAnswers_UserAttempts_UserAttemptId`
    FOREIGN KEY (`UserAttemptId`)
    REFERENCES `capstoneproject`.`userattempts` (`UserAttemptId`)
    ON DELETE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `capstoneproject`.`userprogress`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `capstoneproject`.`userprogress` (
  `UserProgressID` CHAR(36) CHARACTER SET 'ascii' NOT NULL,
  `WatchTime` TIME NOT NULL,
  `TotalTime` TIME NOT NULL,
  `IsWatched` TINYINT(1) NOT NULL,
  `CourseID` CHAR(36) CHARACTER SET 'ascii' NOT NULL,
  `TopicID` CHAR(36) CHARACTER SET 'ascii' NOT NULL,
  `MaterialID` CHAR(36) CHARACTER SET 'ascii' NOT NULL,
  `UserID` CHAR(36) CHARACTER SET 'ascii' NOT NULL,
  PRIMARY KEY (`UserProgressID`),
  INDEX `IX_UserProgress_CourseID` (`CourseID` ASC) VISIBLE,
  INDEX `IX_UserProgress_MaterialID` (`MaterialID` ASC) VISIBLE,
  INDEX `IX_UserProgress_TopicID` (`TopicID` ASC) VISIBLE,
  INDEX `IX_UserProgress_UserID` (`UserID` ASC) VISIBLE,
  CONSTRAINT `FK_UserProgress_Course_CourseID`
    FOREIGN KEY (`CourseID`)
    REFERENCES `capstoneproject`.`course` (`CourseID`)
    ON DELETE CASCADE,
  CONSTRAINT `FK_UserProgress_Materials_MaterialID`
    FOREIGN KEY (`MaterialID`)
    REFERENCES `capstoneproject`.`materials` (`MaterialID`)
    ON DELETE CASCADE,
  CONSTRAINT `FK_UserProgress_Topic_TopicID`
    FOREIGN KEY (`TopicID`)
    REFERENCES `capstoneproject`.`topic` (`TopicID`)
    ON DELETE CASCADE,
  CONSTRAINT `FK_UserProgress_Users_UserID`
    FOREIGN KEY (`UserID`)
    REFERENCES `capstoneproject`.`users` (`UserID`)
    ON DELETE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
